### ISSUE TITLE
environment.yml error even while running via docker

### ISSUE THREAD

**Issue by sangeet2019** [evotools/nf-LO#7]
Hello,

I am having similar issues with creating environment.yml during the workflow run. I am running it using docker using the following command,

nextflow run evotools/nf-LO -with-docker nflo:latest --source source.fa --target target.fa --distance near --aligner lastz --outdir Output_nfLo --profile conda

But, it runs all the way to make_report, and then stalls while trying to create the conda environment, and complains there are lot of versions of the packages in conflict. I thought running it via docker would not cause any issue with dependency. 

Any idea what I may be doing wrong ?

**Comment by RenzoTale88** [comment]
@sangeet2019 thank you for using nf-LO.
Indeed using docker should fix the issue, but to ensure the correct run mode you have to remove the `-profile conda` flag. The latter causes nextflow to use anaconda instead of docker, causing the mentioned issue.
Let me know if it fixes the problems you encounter.
Best
Andrea

**Comment by sangeet2019** [comment]
Thanks for the quick response Andrea. I removed the --profile conda flag, but it is still throwing the same error "Failed to create Conda environment"

**Comment by RenzoTale88** [comment]
Mmm that's curious. I'm working on a better way to manage the configuration. I'll try to test it between today and tomorrow and come back as soon as I push the fix.

**Comment by sangeet2019** [comment]
Great thanks. Let me know when you have an update.

**Comment by RenzoTale88** [comment]
@sangeet2019 I've pushed some changes to the workflow to try fix this bug and a second reported issue. 
I recomment removing the older version of the workflow:
```
nextflow drop evotools/nf-LO
```
And then rerun with the `-with-docker nflo:latest -profile docker` settings.

Please let me know if you come across any further issues.

Best
Andrea

**Comment by sangeet2019** [comment]
Thanks a lot for the fix. It's running now.
